title: SISL Conference Deadlines # (Maintained by @mossr)
description: "Countdowns to deadlines for conference related to research at the <a href='https://sisl.stanford.edu'>Stanford Intelligent Systems Laboratory (SISL)</a>"
author: Robert Moss (forked from Abhishek Das)

domain: "sisl.github.io"
baseurl: "/sisl-deadlines"

twitter_username: SISLaboratory
twitter_hashtag: sisl
github_username: sisl
github_repo: sisl-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
